backend:
  name: git-gateway
  branch: master

media_folder: "images/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts/{{year}}/{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    slug: "index.md"
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }